Fix OSS native Android build
Summary:
The build is failing with:

```
error: undefined reference to 'folly::SharedMutexImpl<false, void, std::__ndk1::atomic, folly::SharedMutexPolicyDefault>::unlock_shared()'
```

Indicating missing link to `folly_futures`.

Changelog: [Internal]

Differential Revision: D34419236

fbshipit-source-id: 86c78933093afa749dcb3be54bae72538eb273e6