ERROR: StaticViewConfigValidator: Invalid static view config for 'AndroidHorizontalScrollView'
Summary:
Add missing scrollsChildToFocus attribute to AndroidHorizontalScrollViewNativeComponent.js
validAttributes to fix StaticViewConfigValidator error.

The native Android side (ReactHorizontalScrollViewManager.kt) defines scrollsChildToFocus as a ReactProp, but the JavaScript static view config was missing this attribute.

This fixes the error:
ERROR StaticViewConfigValidator: Invalid static view config for 'AndroidHorizontalScrollView'. 'validAttributes.scrollsChildToFocus' is missing.


Changelog: [Internal]

Reviewed By: javache

Differential Revision: D91480519