Add missing <algorithm> import in (#37262)
Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/37262

Fix compile errors on Windows as
```
stderr:react-native-github\packages\react-native\ReactCommon\react\renderer\componentregistry\componentNameByReactViewName.cpp(18,12): error: no member named 'mismatch' in namespace 'std'
  if (std::mismatch(rctPrefix.begin(), rctPrefix.end(), viewName.begin())
      ~~~~~^
```

Changelog: [Internal]

Reviewed By: javache

Differential Revision: D45597108

fbshipit-source-id: 5741f88c55a3bc956c77d83e083a167a68d78d32