Update fbjs version
`react-relay` requires fbjs@0.7 to be installed, otherwise a naming collision happens:
```bash
Error: Naming collision detected: /some/path/node_modules/fbjs/package.json collides with > /some/path/node_modules/react-relay/node_modules/fbjs/package.json
```