Fix unused exception parameter compile error in RCTUIManager catch block
Summary:
In some configurations the errors might be stripped out and leading toward those kind of issues:

```
stderr:

xplat/js/react-native-github/packages/react-native/React/Modules/RCTUIManager.mm:1251:28: error: unused exception parameter 'exception' [-Werror,-Wunused-exception-parameter]

 1251 |     } catch (NSException \*exception) {

      |                            ^\~\~\~\~\~\~\~\~

1 error generated.
```

So marking the param as potentially unused.

Reviewed By: lodhaayush

Differential Revision: D90192993