Fix instacrash on main for Release due to java.lang.NoSuchMethodError (#37550)
Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/37550

RN Tester is instacrashing on Android on main sadly since a while.
I've noticed it while working on another diff. The crash is a native crash with message:

```
Abort message: 'terminating with uncaught exception of type facebook::jni::JniException: java.lang.NoSuchMethodError: no non-static method "Lcom/facebook/react/fabric/events/EventEmitterWrapper;.<init>(Lcom/facebook/jni/HybridData;)V"'
```

which happens because this method is stripped by proguard. I'm fixing it here.

Changelog:
[Android] [Fixed] - Fix instacrash on main for Release due to java.lang.NoSuchMethodError

Reviewed By: cipolleschi

Differential Revision: D46145613

fbshipit-source-id: c2164dfc931651a6b8d6283552de0da89fa11f02