Expose `oscompat` headers via prefab (#55242)
Summary:
This PR fixes the following build error while trying to build `react-native@0.83.1` app with `react-native-worklets@0.7.1` installed using react-native prebuilds (AAR) due to a missing `oscompat/OSCompat.h` file in `prefab/modules/` inside `react-android-0.83.1-debug.aar`.

```
In file included from /Users/war-in/WebstormProjects/react-native-live-markdown-fork/example/node_modules/react-native-worklets/android/build/prefab-headers/worklets/worklets/WorkletRuntime/WorkletRuntime.h:5:
In file included from /Users/war-in/WebstormProjects/react-native-live-markdown-fork/node_modules/react-native/ReactCommon/jsiexecutor/jsireact/JSIExecutor.h:11:
In file included from /Users/war-in/.gradle/caches/9.0.0/transforms/f97a0c8835e876dfb08e8efd6d33fd2f/transformed/react-android-0.83.1-debug/prefab/modules/reactnative/include/cxxreact/JSExecutor.h:16:
In file included from /Users/war-in/.gradle/caches/9.0.0/transforms/f97a0c8835e876dfb08e8efd6d33fd2f/transformed/react-android-0.83.1-debug/prefab/modules/reactnative/include/jsinspector-modern/ReactCdp.h:11:
In file included from /Users/war-in/.gradle/caches/9.0.0/transforms/f97a0c8835e876dfb08e8efd6d33fd2f/transformed/react-android-0.83.1-debug/prefab/modules/reactnative/include/jsinspector-modern/FallbackRuntimeTargetDelegate.h:11:
In file included from /Users/war-in/.gradle/caches/9.0.0/transforms/f97a0c8835e876dfb08e8efd6d33fd2f/transformed/react-android-0.83.1-debug/prefab/modules/reactnative/include/jsinspector-modern/RuntimeTarget.h:14:
In file included from /Users/war-in/.gradle/caches/9.0.0/transforms/f97a0c8835e876dfb08e8efd6d33fd2f/transformed/react-android-0.83.1-debug/prefab/modules/reactnative/include/jsinspector-modern/RuntimeAgent.h:16:
In file included from /Users/war-in/.gradle/caches/9.0.0/transforms/f97a0c8835e876dfb08e8efd6d33fd2f/transformed/react-android-0.83.1-debug/prefab/modules/reactnative/include/jsinspector-modern/tracing/TargetTracingAgent.h:10:
/Users/war-in/.gradle/caches/9.0.0/transforms/f97a0c8835e876dfb08e8efd6d33fd2f/transformed/react-android-0.83.1-debug/prefab/modules/reactnative/include/jsinspector-modern/tracing/TraceRecordingState.h:14:10: fatal error: 'oscompat/OSCompat.h' file not found
   14 | #include <oscompat/OSCompat.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
```

## Changelog:

[ANDROID] [CHANGED] - Expose `oscompat` headers via prefab

Pull Request resolved: https://github.com/facebook/react-native/pull/55242

Reviewed By: cipolleschi

Differential Revision: D91031822

Pulled By: cortinico

fbshipit-source-id: f69b48bd84c08c4b1545c44ed0c55e6a83c6ac64