Update Flipper in template
Summary:
Same steps as in RNTester.

Test Plan:
react-native init --version 0.62.0-rc.0

Effectively made the same changes as below. Compiles but currently
doesn't run because of an unrelated crash:

```
	14:35:54.053	AndroidRuntime	FATAL EXCEPTION: mqt_native_modules
Process: com.testproj, PID: 29797
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
	at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:190)
	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:830)
	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:189)
	at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:157)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:149)
	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:590)
	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:567)
	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:42)
	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1111)
	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1057)
	at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:132)
	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1017)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:214)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout" on path: DexPathList[[zip file "/data/app/com.testproj-aGTaaMSONCephW7Vd5X-lA==/base.apk"],nativeLibraryDirectories=[/data/app/com.testproj-aGTaaMSONCephW7Vd5X-lA==/lib/x86, /data/app/com.testproj-aGTaaMSONCephW7Vd5X-lA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 22 more

```