ERROR: StaticViewConfigValidator: Invalid static view config for 'AndroidHorizontalScrollView' (#55299)
Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/55299

Add missing scrollsChildToFocus attribute to AndroidHorizontalScrollViewNativeComponent.js
validAttributes to fix StaticViewConfigValidator error.

The native Android side (ReactHorizontalScrollViewManager.kt) defines scrollsChildToFocus as a ReactProp, but the JavaScript static view config was missing this attribute.

This fixes the error:
ERROR StaticViewConfigValidator: Invalid static view config for 'AndroidHorizontalScrollView'. 'validAttributes.scrollsChildToFocus' is missing.

Changelog: [Internal]

Reviewed By: javache

Differential Revision: D91480519

fbshipit-source-id: d70b93467fe313838e268d95f98010d67197c3b4