Update setup.js
Jest test are failing if component is using Platform module. 
react-native 0.39.2
react: 15.4.1
Error: 
 TypeError: Cannot read property 'osVersion' of undefined
 at Object.get Version [as Version] (node_modules/react-native/Libraries/Utilities/Platform.ios.js:18:45)

With this pull request default platform is IOS. Should be dynamic based on package.json jest configuration if is defined.