Actually fix `java.lang.NoSuchMethodError` for Bridgeless (#41081)
Summary:

It turns out that Bridgeless for RN-Tester release is still broken.
This fixes it by making sure we actually `DoNotStrip` the missing constructor

Changelog:
[Android] [Fixed] - Fix crash with `java.lang.NoSuchMethodError` for Bridgeless

Reviewed By: RSNara

Differential Revision: D50455967